#!/usr/bin/perl -l
use strict;
use warnings;
use IO::Socket;

my $port = shift or die "missing arg";

my $server = IO::Socket::INET -> new (Proto => "tcp",
	LocalPort => $port,
	Listen => 16000,
	Reuse => 1);

die "Ne peux pas creer de socket sur le port $port: $!" unless $server;
$SIG{"CHLD"}="IGNORE";

our %h=();

my @liste_client_sockets=();

sub welcome {
    my $client = shift;
    print $client "USER";
    my $name=<$client>;
    if(defined $h{$name}){
	print $client "BAD_USER";
    }else{
	$h{$name}=1;
	print $client "OK";
    }
}

while (my $client = $server -> accept() ) {
	my $pid = fork();
	if (!defined $pid) {
		#erreur
	}
	elsif ($pid) {
		push @liste_client_sockets, $pid;
		}
		else {
			welcome($client, %h);
			while (1) {
				my $requete = "";
				$requete .= <$client>;
				chomp $requete;
			}
		}
	}
